/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/UI/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/UI/AppHeader.vue')['default']
    BarPlot: typeof import('./src/components/viz/BarPlot.vue')['default']
    CarouselContent: typeof import('./src/components/UI/CarouselContent.vue')['default']
    City_scatter_bar: typeof import('./src/components/viz/city_scatter_bar.vue')['default']
    ColorPalette: typeof import('./src/components/UI/ColorPalette.vue')['default']
    DataDownload: typeof import('./src/components/UI/DataDownload.vue')['default']
    DataVizTS: typeof import('./src/components/viz/DataVizTS.vue')['default']
    DisclaimerPopup: typeof import('./src/components/UI/DisclaimerPopup.vue')['default']
    Fact_row: typeof import('./src/components/fact_row.vue')['default']
    FooterColumn1: typeof import('./src/components/UI/FooterColumn1.vue')['default']
    FooterColumn2: typeof import('./src/components/UI/FooterColumn2.vue')['default']
    FooterColumn3: typeof import('./src/components/UI/FooterColumn3.vue')['default']
    GalleryComponent: typeof import('./src/components/UI/GalleryComponent.vue')['default']
    GridMapEchart: typeof import('./src/components/viz/GridMapEchart.vue')['default']
    IndianCitiesMap: typeof import('./src/components/viz/IndianCitiesMap.vue')['default']
    LogoStatus: typeof import('./src/components/UI/LogoStatus.vue')['default']
    Method_animation: typeof import('./src/components/UI/method_animation.vue')['default']
    Method_animation2: typeof import('./src/components/UI/method_animation2.vue')['default']
    MethodPopup: typeof import('./src/components/UI/MethodPopup.vue')['default']
    ProgressLoader: typeof import('./src/components/UI/ProgressLoader.vue')['default']
    ProjectTitle: typeof import('./src/components/UI/ProjectTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamMemberCard: typeof import('./src/components/UI/TeamMemberCard.vue')['default']
    TeamSection: typeof import('./src/components/UI/TeamSection.vue')['default']
    TimelineComponent: typeof import('./src/components/UI/TimelineComponent.vue')['default']
    TimeSeriesPlot: typeof import('./src/components/viz/TimeSeriesPlot.vue')['default']
  }
}
